--- #YAML:1.0
name:               Mojolicious-Plugin-YamlConfig
version:            0.0.2
abstract:           YAML Configuration Plugin for Mojolicious
author:
    - Danijel Tasov <data@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  6.31
build_requires:  {}
requires:
    Mojolicious:  0.999927
    YAML::Any:    0
resources:
    license:     http://dev.perl.org/licenses/
    repository:  http://github.com/datamuc/Mojolicious-Plugin-YamlConfig
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
