---
abstract: 'YAML Configuration Plugin for Mojolicious'
author:
  - 'Danijel Tasov <data@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120351'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-YamlConfig
no_index:
  directory:
    - t
    - inc
requires:
  Mojolicious: 1.80
  YAML::Tiny: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/datamuc/Mojolicious-Plugin-YamlConfig
version: v0.1.5
